desc 'Ship to Testflight'
lane :beta do
  setup_ci if ENV['CI']
  match(app_identifier: 'com.leqg.app', type: 'appstore', readonly: true)
  increment_build_number(build_number: ENV['BUILD_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')
  increment_version_number(version_number: ENV['VERSION_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')
  build_app(scheme: 'leqg', workspace: './ios/leqg.xcworkspace', silent: true)
  upload_to_testflight(skip_waiting_for_build_processing: true)
end
