desc 'Ship to Testflight'
lane :beta do
  setup_ci if ENV['CI']
  match(app_identifier: 'com.leqg.app', type: 'appstore', readonly: true)
  api_key = app_store_connect_api_key

  increment_build_number(build_number: ENV['BUILD_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')
  increment_version_number(version_number: ENV['VERSION_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')

  build_app(scheme: 'leqg', workspace: './ios/leqg.xcworkspace', silent: true, suppress_xcode_output: true)
  upload_to_testflight(api_key: api_key)
end

desc 'Deploy to App Store'
lane :release do
  setup_ci if ENV['CI']
  match(app_identifier: 'com.leqg.app', type: 'appstore', readonly: true)
  api_key = app_store_connect_api_key

  increment_build_number(build_number: ENV['BUILD_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')
  increment_version_number(version_number: ENV['VERSION_NUMBER'], xcodeproj: './ios/leqg.xcodeproj')

  build_app(scheme: 'leqg', workspace: './ios/leqg.xcworkspace', silent: true, suppress_xcode_output: true)
  upload_to_app_store(api_key: api_key, force: true)
end
