name: Deploy iOS

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache Node.js dependencies
        id: cache-nodejs-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-nodejs-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Cache iOS dependencies
        id: cache-ios-dependencies
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ hashFiles('**/Podfile.lock') }}
      - name: Install iOS dependencies
        if: steps.cache-ios-dependencies.outputs.cache-hit != 'true'
        run: pod install
        working-directory: ios

      # - name: Unit tests
      #   run: yarn test

      # - name: Get release version
      #   run: echo "RELEASE_VERSION=1.0.3" >> $GITHUB_ENV

      # - run: fastlane beta
      #   env:
      #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      #     MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      #     MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_REPO_TOKEN_64 }}
      #     BUILD_NUMBER: ${{ github.run_number }}
      #     VERSION_NUMBER: ${{ env.RELEASE_VERSION }}
